-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2026-09-20 02:07:57 SAST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE Customer 
    ( 
     Customer_ID   NUMBER  NOT NULL , 
     FIRST_NAME    VARCHAR2 (100)  NOT NULL , 
     LAST_NAME     VARCHAR2 (100)  NOT NULL , 
     PHONE_NUMBER  VARCHAR2 (20)  NOT NULL , 
     EMAIL_ADDRESS VARCHAR2 (100) 
    ) 
;

ALTER TABLE Customer 
    ADD CONSTRAINT Customer_PK PRIMARY KEY ( Customer_ID ) ;

CREATE TABLE INTAKE 
    ( 
     INTAKE_ID          NUMBER  NOT NULL , 
     INTAKE_TIMESTAMP   TIMESTAMP  NOT NULL , 
     WAIVER_AGREED      VARCHAR2 (1)  NOT NULL , 
     WAIVER_SIGNATURE   VARCHAR2 (255)  NOT NULL , 
     VEHICLE_VEHICLE_ID NUMBER  NOT NULL 
    ) 
;

ALTER TABLE INTAKE 
    ADD CONSTRAINT INTAKE_PK PRIMARY KEY ( INTAKE_ID ) ;

CREATE TABLE RESERVATION 
    ( 
     RESERVATION_ID       NUMBER  NOT NULL , 
     BOOKING_DATE         DATE  NOT NULL , 
     TIME_SLOT            VARCHAR2 (20)  NOT NULL , 
     IS_OFF_PEAK          VARCHAR2 (1)  NOT NULL , 
     DISCOUNT_APPLIED     NUMBER (5,2) , 
     Customer_Customer_ID NUMBER  NOT NULL , 
     VEHICLE_VEHICLE_ID   NUMBER  NOT NULL 
    ) 
;

ALTER TABLE RESERVATION 
    ADD CONSTRAINT RESERVATION_PK PRIMARY KEY ( RESERVATION_ID ) ;

CREATE TABLE SERVICE_QUEUE 
    ( 
     QUEUE_ID                  NUMBER  NOT NULL , 
     STATUS                    VARCHAR2 (20)  NOT NULL , 
     BAY_NUMBER                NUMBER , 
     ESTIMATED_COMPLETION_TIME TIMESTAMP  NOT NULL , 
     INTAKE_INTAKE_ID          NUMBER  NOT NULL 
    ) 
;

ALTER TABLE SERVICE_QUEUE 
    ADD CONSTRAINT SERVICE_QUEUE_PK PRIMARY KEY ( QUEUE_ID ) ;

CREATE TABLE VALUABLES_AUDIT 
    ( 
     ITEM_ID          NUMBER  NOT NULL , 
     ITEM_DESCRIPTION VARCHAR2 (255)  NOT NULL , 
     CATEGORY         VARCHAR2 (50)  NOT NULL , 
     INTAKE_INTAKE_ID NUMBER  NOT NULL 
    ) 
;

ALTER TABLE VALUABLES_AUDIT 
    ADD CONSTRAINT VALUABLES_AUDIT_PK PRIMARY KEY ( ITEM_ID ) ;

CREATE TABLE VEHICLE 
    ( 
     VEHICLE_ID           NUMBER  NOT NULL , 
     LICENSE_PLATE        VARCHAR2 (20)  NOT NULL , 
     MAKE_MODEL           VARCHAR2 (100)  NOT NULL , 
     COLOR                VARCHAR2 (30)  NOT NULL , 
     Customer_Customer_ID NUMBER  NOT NULL 
    ) 
;

ALTER TABLE VEHICLE 
    ADD CONSTRAINT VEHICLE_PK PRIMARY KEY ( VEHICLE_ID ) ;

ALTER TABLE INTAKE 
    ADD CONSTRAINT INTAKE_VEHICLE_FK FOREIGN KEY 
    ( 
     VEHICLE_VEHICLE_ID
    ) 
    REFERENCES VEHICLE 
    ( 
     VEHICLE_ID
    ) 
;

ALTER TABLE RESERVATION 
    ADD CONSTRAINT RESERVATION_Customer_FK FOREIGN KEY 
    ( 
     Customer_Customer_ID
    ) 
    REFERENCES Customer 
    ( 
     Customer_ID
    ) 
;

ALTER TABLE RESERVATION 
    ADD CONSTRAINT RESERVATION_VEHICLE_FK FOREIGN KEY 
    ( 
     VEHICLE_VEHICLE_ID
    ) 
    REFERENCES VEHICLE 
    ( 
     VEHICLE_ID
    ) 
;

ALTER TABLE SERVICE_QUEUE 
    ADD CONSTRAINT SERVICE_QUEUE_INTAKE_FK FOREIGN KEY 
    ( 
     INTAKE_INTAKE_ID
    ) 
    REFERENCES INTAKE 
    ( 
     INTAKE_ID
    ) 
;

ALTER TABLE VALUABLES_AUDIT 
    ADD CONSTRAINT VALUABLES_AUDIT_INTAKE_FK FOREIGN KEY 
    ( 
     INTAKE_INTAKE_ID
    ) 
    REFERENCES INTAKE 
    ( 
     INTAKE_ID
    ) 
;

ALTER TABLE VEHICLE 
    ADD CONSTRAINT VEHICLE_Customer_FK FOREIGN KEY 
    ( 
     Customer_Customer_ID
    ) 
    REFERENCES Customer 
    ( 
     Customer_ID
    ) 
;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             6
-- CREATE INDEX                             0
-- ALTER TABLE                             12
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
